### ISSUE TITLE
Branding of the FileVault auth-restart dialog

### ISSUE THREAD

**Issue by miikkali** [ox-it/munki-rebrand#15]
I was testing munki_rebrand.py with Munki 3.0.0.3316. When Munki starts the macOS install process, it appears that the FileVault auth-restart dialog is not rebranded. It still tells "Managed Software Center wants to unlock the startup disk..." when I would expect it to tell "$my-rebranded-software-centre wants to unlock the startup disk..."

<img width="552" alt="screen shot 2017-05-17 at 10 57 59" src="https://cloud.githubusercontent.com/assets/15377733/26163090/3ee983b8-3b31-11e7-9eb1-e0ab28c66e00.png">

**Comment by fuzzylogiq** [comment]
I'm assuming this is being run without `-l` and is being viewed in US English. If so, I think that https://github.com/ox-it/munki-rebrand/commit/f80c6d0bd0bc6cee4be022407644e0d09b5d6ac9 should fix it. Can you test and let me know?

**Comment by miikkali** [comment]
I was running with `--localized`

The test machine (as all our Macs) has language and locale set like this:

```
	<key>AppleLanguages</key>
		<array>
		<string>en-FI</string>
		</array>
	<key>AppleLocale</key>
		<string>en_FI</string>
		<key>Country</key>
		<string>FI</string>
```

In SysPrefs/Language & Region this setting shows the language as "English". I have no idea how that is different from the ten or so other Englishes on the list, which include the U.K. and U.S. variations among others.

I will test tomorrow before noon (UTC+2). 

Thanks!

**Comment by fuzzylogiq** [comment]
Ok en-FI is not something I have encountered before, but I'm assuming the interface is in English with certain other parts (numbers/dates) in your locale's style. In this case you _probably_ don't need to use --localized/--l as I think you are using the neutral "English" (which I perhaps wrongly equate with US English) so all you need is for the English originals to be substituted and not any Finnish translations. In any case, this was not happening for the new window controller Greg had included in the latest betas of Munki3 so the commit should fix this.

**Comment by miikkali** [comment]
Yes, your assumption is correct in that the `FI` part in `en-FI` relates to date formatting and such locale style. To my knowledge, it shouldn't affect language, only locale.

We use --localized because we have users who might need to change the default macOS language from English to something else, and I would like them to still see our rebranded Munki in English like everyone else. If you are a visiting professor from Russia and want to change your macOS language to Russian, you should still see the same English language $our-rebranded-software-centre like all the other users who might have English or Finnish or whatever language set as their preferred language in SysPrefs.

Anyway, I'll test f80c6d0 tomorrow and come back.

**Comment by miikkali** [comment]
Big thanks @fuzzylogiq ! f80c6d0 fixed it!
